from unittest.mock import patch

import frappe
from frappe.tests import IntegrationTestCase

from india_compliance.gst_india.api_classes.nic.e_waybill import (
    EnrichedEWaybillAPI,
    EWaybillAPI,
    StandardEWaybillAPI,
)


class TestEWaybillAPI(IntegrationTestCase):
    def test_create_returns_standard_in_normal_mode(self):
        mock_settings = frappe._dict(
            sandbox_mode=False, use_fallback_for_nic=False, api_secret="test-secret"
        )
        mock_settings.get_password = lambda *a, **kw: "test-secret"
        with patch.object(frappe, "get_cached_doc", return_value=mock_settings):
            with patch(
                "india_compliance.gst_india.api_classes.base.is_api_enabled",
                return_value=True,
            ):
                with patch.object(StandardEWaybillAPI, "setup"):
                    api = EWaybillAPI.create()

        self.assertIsInstance(api, StandardEWaybillAPI)

    def test_create_returns_enriched_in_sandbox_mode(self):
        mock_settings = frappe._dict(
            sandbox_mode=True, use_fallback_for_nic=False, api_secret="test-secret"
        )
        mock_settings.get_password = lambda *a, **kw: "test-secret"
        with patch.object(frappe, "get_cached_doc", return_value=mock_settings):
            with patch(
                "india_compliance.gst_india.api_classes.base.is_api_enabled",
                return_value=True,
            ):
                with patch.object(EnrichedEWaybillAPI, "setup"):
                    api = EWaybillAPI.create()

        self.assertIsInstance(api, EnrichedEWaybillAPI)

    def test_create_returns_enriched_when_using_fallback(self):
        mock_settings = frappe._dict(
            sandbox_mode=False, use_fallback_for_nic=True, api_secret="test-secret"
        )
        mock_settings.get_password = lambda *a, **kw: "test-secret"
        with patch.object(frappe, "get_cached_doc", return_value=mock_settings):
            with patch(
                "india_compliance.gst_india.api_classes.base.is_api_enabled",
                return_value=True,
            ):
                with patch.object(EnrichedEWaybillAPI, "setup"):
                    api = EWaybillAPI.create()

        self.assertIsInstance(api, EnrichedEWaybillAPI)

    def test_validate_enable_api_raises_when_e_waybill_disabled(self):
        api = EWaybillAPI.__new__(EWaybillAPI)
        api.settings = frappe._dict(enable_e_waybill=False)

        with self.assertRaises(frappe.ValidationError):
            api.validate_enable_api()

    def test_validate_enable_api_succeeds_when_enabled(self):
        api = EWaybillAPI.__new__(EWaybillAPI)
        api.settings = frappe._dict(enable_e_waybill=True)

        api.validate_enable_api()

    def test_is_ignored_error_returns_true_for_238(self):
        api = EWaybillAPI.__new__(EWaybillAPI)
        response = frappe._dict(message="Invalid auth token")

        result = api.is_ignored_error(response)

        self.assertTrue(result)
        self.assertEqual(response.error_code, "238")

    def test_is_ignored_error_returns_true_for_312(self):
        api = EWaybillAPI.__new__(EWaybillAPI)
        response = frappe._dict(
            message="This eway bill is either not generated by you or cancelled"
        )

        result = api.is_ignored_error(response)

        self.assertTrue(result)
        self.assertEqual(response.error_code, "312")

    def test_is_ignored_error_returns_true_for_328(self):
        api = EWaybillAPI.__new__(EWaybillAPI)
        response = frappe._dict(
            message="Could not retrieve transporter details from gstin"
        )

        result = api.is_ignored_error(response)

        self.assertTrue(result)
        self.assertEqual(response.error_code, "328")

    def test_is_ignored_error_returns_false_for_unknown_message(self):
        api = EWaybillAPI.__new__(EWaybillAPI)
        response = frappe._dict(message="Some unknown error")

        result = api.is_ignored_error(response)

        self.assertFalse(result)

    def test_is_ignored_error_returns_false_for_empty_message(self):
        api = EWaybillAPI.__new__(EWaybillAPI)
        response = frappe._dict(message="")

        result = api.is_ignored_error(response)

        self.assertFalse(result)

    def test_get_e_waybill_uses_getewaybill_in_sandbox_mode(self):
        api = EWaybillAPI.__new__(EWaybillAPI)
        api.sandbox_mode = True

        with patch.object(api, "get") as mock_get:
            api.get_e_waybill("123456789")

        mock_get.assert_called_once_with(
            "getewaybill", params={"ewbNo": "123456789"}
        )

    def test_get_e_waybill_uses_GetEwayBill_in_normal_mode(self):
        api = EWaybillAPI.__new__(EWaybillAPI)
        api.sandbox_mode = False

        with patch.object(api, "get") as mock_get:
            api.get_e_waybill("123456789")

        mock_get.assert_called_once_with(
            "GetEwayBill", params={"ewbNo": "123456789"}
        )

    def test_update_distance_parses_alert_with_distance(self):
        api = EWaybillAPI.__new__(EWaybillAPI)
        result = frappe._dict(alert="Distance 125 km")

        api.update_distance(result)

        self.assertEqual(result.distance, 125)

    def test_update_distance_skips_when_no_alert_key(self):
        api = EWaybillAPI.__new__(EWaybillAPI)
        result = frappe._dict()

        api.update_distance(result)

        self.assertIsNone(result.get("distance"))

    def test_update_distance_skips_when_alert_lacks_distance_word(self):
        api = EWaybillAPI.__new__(EWaybillAPI)
        result = frappe._dict(alert="No distance info here")

        api.update_distance(result)

        self.assertIsNone(result.get("distance"))


class TestStandardEWaybillAPI(IntegrationTestCase):
    def test_is_ignored_error_returns_true_for_238(self):
        api = StandardEWaybillAPI.__new__(StandardEWaybillAPI)
        response = frappe._dict(error=frappe._dict(errorCodes="238,312"))

        result = api.is_ignored_error(response)

        self.assertTrue(result)
        self.assertEqual(response.error_code, "238")
        self.assertEqual(response.error_message, "Invalid auth token")

    def test_is_ignored_error_returns_false_when_no_error_codes(self):
        api = StandardEWaybillAPI.__new__(StandardEWaybillAPI)
        response = frappe._dict(error=frappe._dict())

        result = api.is_ignored_error(response)

        self.assertFalse(result)

    def test_is_ignored_error_returns_false_when_no_error_key(self):
        api = StandardEWaybillAPI.__new__(StandardEWaybillAPI)
        response = frappe._dict()

        result = api.is_ignored_error(response)

        self.assertFalse(result)
