pull_request_rules:
  - name: Auto-close PRs on stable branch
    conditions:
      - and:
          - author!=sagarvora
          - author!=vorasmit
          - author!=mergify[bot]
          - author!=dependabot[bot]
          - base=version-14
    actions:
      close:
      comment:
          message: |
            @{{author}}, thanks for the contribution, but we do not accept pull requests on a stable branch. Please raise PR on the `next` branch.

  - name: Automatic merge on CI success and review
    conditions:
      - label!=dont-merge
      - label!=squash
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
  
  - name: Automatic squash on CI success and review
    conditions:
      - label!=dont-merge
      - label=squash
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: squash
        commit_message_template: |
            {{ title }} (#{{ number }})
            {{ body }}
  
  - name: backport to develop
    conditions:
      - label="backport next"
    actions:
      backport:
        branches:
          - next
        assignees:
          - "{{ author }}"
          
  - name: backport to version-14-hotfix
    conditions:
      - label="backport version-14-hotfix"
    actions:
      backport:
        branches:
          - version-14-hotfix
        assignees:
          - "{{ author }}"
