pull_request_rules:
    - name: backport to develop
      conditions:
          - label="backport develop"
      actions:
          backport:
              branches:
                  - develop
              assignees:
                  - "{{ author }}"

    - name: backport to version-14-hotfix
      conditions:
          - label="backport version-14-hotfix"
      actions:
          backport:
              branches:
                  - version-14-hotfix
              assignees:
                  - "{{ author }}"
