codecov:
  require_ci_to_pass: true

comment:
  behavior: default
  layout: reach,diff,flags,tree,reach
  show_carryforward_flags: false

coverage:
  precision: 2
  round: down
  status:
    changes: false
    default_rules:
      flag_coverage_not_uploaded_behavior: include
    
    patch:
      default:
        base: auto
        branches:
        - ^develop$
        if_ci_failed: ignore
        only_pulls: true
        target: 85%
        threshold: 1%
    
    project: 
      default:
        base: auto
        threshold: 20%

github_checks:
  annotations: true
