name: Bug Report
description: Report a bug encountered while using India Compliance
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Welcome to India Compliance issue tracker! Prior to submitting a request, kindly consider the following:

        1. This tracker should only be used to report bugs and request features / enhancements to India Compliance
            - For questions and general support, checkout the [documentation](https://docs.erpnext.com/docs/v14/user/manual/en/regional/india).
            - For documentation issues, propose edit on documentation site directly.
        2. Use the search function before creating a new issue. Duplicates will be closed and directed to
           the original discussion.    
        3. When making a bug report, make sure you provide all required information. The easier it is for
           maintainers to reproduce, the faster it'll be fixed.
        4. If you think you know what the reason for the bug is, share it with us. Maybe put in a PR 😉

  - type: textarea
    id: bug-info
    attributes:
      label: Information about bug
      description: Also tell us, what did you expect to happen?
                   If applicable, add screenshots to help explain your problem. 
      placeholder: Please provide as much information as possible.
    validations:
      required: true

  - type: textarea
    id: exact-version
    attributes:
      label: Version
      description: Share exact version number of Frappe and ERPNext and India Compliance you are using.
      placeholder: |
        Frappe Version -
        ERPNext Verion -
        India Compliance Version - 
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output / Stack trace / Full Error Message.
      description: Please copy and paste any relevant log output. This will be automatically formatted.
      render: shell

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/resilient-tech/india-compliance/blob/next/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
          