from frappe.tests.utils import FrappeTestCase, change_settings
from frappe.utils import getdate

from india_compliance.gst_india.report.gst_sales_register_beta.gst_sales_register_beta import (
    execute,
)
from india_compliance.gst_india.utils.tests import create_sales_invoice

today = getdate()

FILTERS = {
    "company": "_Test Indian Registered Company",
    "date_range": [today, today],
    "from_date": today,
    "to_date": today,
}

EXPECTED_OUTPUT = {
    "SUMMARY_BY_ITEM": [
        {
            "item_code": "_Test Trading Goods 1",
            "gst_hsn_code": "61149090",
            "uom": "Nos",
            "billing_address_gstin": None,
            "company_gstin": "24AAQCA8719H1ZC",
            "customer_name": "_Test Unregistered Customer",
            "posting_date": today,
            "place_of_supply": "29-Karnataka",
            "is_reverse_charge": 0,
            "is_export_with_gst": 0,
            "is_return": 0,
            "is_debit_note": 0,
            "return_against": None,
            "invoice_total": 472000.0,
            "returned_invoice_total": 0.0,
            "gst_category": "Unregistered",
            "gst_treatment": "Taxable",
            "gst_rate": 18.0,
            "taxable_value": 400000.0,
            "cgst_amount": 0.0,
            "sgst_amount": 0.0,
            "igst_amount": 72000.0,
            "cess_amount": 0.0,
            "cess_non_advol_amount": 0.0,
            "total_cess_amount": 0.0,
            "total_tax": 72000.0,
            "total_amount": 472000.0,
            "invoice_category": "B2C (Large)",
            "invoice_sub_category": "B2C (Large)",
        },
        {
            "item_code": "_Test Trading Goods 1",
            "gst_hsn_code": "61149090",
            "uom": "Nos",
            "billing_address_gstin": None,
            "company_gstin": "24AAQCA8719H1ZC",
            "customer_name": "_Test Unregistered Customer",
            "posting_date": today,
            "place_of_supply": "24-Gujarat",
            "is_reverse_charge": 0,
            "is_export_with_gst": 0,
            "is_return": 0,
            "is_debit_note": 0,
            "return_against": None,
            "invoice_total": 472000.0,
            "returned_invoice_total": 0.0,
            "gst_category": "Unregistered",
            "gst_treatment": "Taxable",
            "gst_rate": 18.0,
            "taxable_value": 400000.0,
            "cgst_amount": 36000.0,
            "sgst_amount": 36000.0,
            "igst_amount": 0.0,
            "cess_amount": 0.0,
            "cess_non_advol_amount": 0.0,
            "total_cess_amount": 0.0,
            "total_tax": 72000.0,
            "total_amount": 472000.0,
            "invoice_category": "B2C (Others)",
            "invoice_sub_category": "B2C (Others)",
        },
        {
            "item_code": "_Test Nil Rated Item",
            "gst_hsn_code": "61149090",
            "uom": "Nos",
            "billing_address_gstin": None,
            "company_gstin": "24AAQCA8719H1ZC",
            "customer_name": "_Test Unregistered Customer",
            "posting_date": today,
            "place_of_supply": "24-Gujarat",
            "is_reverse_charge": 0,
            "is_export_with_gst": 0,
            "is_return": 0,
            "is_debit_note": 0,
            "return_against": None,
            "invoice_total": 400000.0,
            "returned_invoice_total": 0.0,
            "gst_category": "Unregistered",
            "gst_treatment": "Nil-Rated",
            "gst_rate": 0.0,
            "taxable_value": 400000.0,
            "cgst_amount": 0.0,
            "sgst_amount": 0.0,
            "igst_amount": 0.0,
            "cess_amount": 0.0,
            "cess_non_advol_amount": 0.0,
            "total_cess_amount": 0.0,
            "total_tax": 0.0,
            "total_amount": 400000.0,
            "invoice_category": "Nil-Rated,Exempted,Non-GST",
            "invoice_type": "Intra-State to unregistered persons",
            "invoice_sub_category": "Nil-Rated",
        },
        {
            "item_code": "_Test Trading Goods 1",
            "gst_hsn_code": "61149090",
            "uom": "Nos",
            "billing_address_gstin": "29AABCR1718E1ZL",
            "company_gstin": "24AAQCA8719H1ZC",
            "customer_name": "_Test Registered Composition Customer",
            "posting_date": today,
            "place_of_supply": "29-Karnataka",
            "is_reverse_charge": 0,
            "is_export_with_gst": 0,
            "is_return": 0,
            "is_debit_note": 0,
            "return_against": None,
            "invoice_total": 472000.0,
            "returned_invoice_total": 0.0,
            "gst_category": "Registered Composition",
            "gst_treatment": "Taxable",
            "gst_rate": 18.0,
            "taxable_value": 400000.0,
            "cgst_amount": 0.0,
            "sgst_amount": 0.0,
            "igst_amount": 72000.0,
            "cess_amount": 0.0,
            "cess_non_advol_amount": 0.0,
            "total_cess_amount": 0.0,
            "total_tax": 72000.0,
            "total_amount": 472000.0,
            "invoice_category": "B2B,SEZ,DE",
            "invoice_type": "Regular B2B",
            "invoice_sub_category": "B2B Regular",
        },
        {
            "item_code": "_Test Trading Goods 1",
            "gst_hsn_code": "61149090",
            "uom": "Nos",
            "billing_address_gstin": "29AABCR1718E1ZL",
            "company_gstin": "24AAQCA8719H1ZC",
            "customer_name": "_Test Registered Composition Customer",
            "posting_date": today,
            "place_of_supply": "29-Karnataka",
            "is_reverse_charge": 0,
            "is_export_with_gst": 0,
            "is_return": 1,
            "is_debit_note": 0,
            "return_against": None,
            "invoice_total": -472000.0,
            "returned_invoice_total": 0.0,
            "gst_category": "Registered Composition",
            "gst_treatment": "Taxable",
            "gst_rate": 18.0,
            "taxable_value": -400000.0,
            "cgst_amount": 0.0,
            "sgst_amount": 0.0,
            "igst_amount": -72000.0,
            "cess_amount": 0.0,
            "cess_non_advol_amount": 0.0,
            "total_cess_amount": 0.0,
            "total_tax": -72000.0,
            "total_amount": -472000.0,
            "invoice_category": "Credit/Debit Notes (Registered)",
            "invoice_type": "Regular B2B",
            "invoice_sub_category": "CDNR",
        },
        {
            "item_code": "_Test Trading Goods 1",
            "gst_hsn_code": "61149090",
            "uom": "Nos",
            "billing_address_gstin": None,
            "company_gstin": "24AAQCA8719H1ZC",
            "customer_name": "_Test Foreign Customer",
            "posting_date": today,
            "place_of_supply": "96-Other Countries",
            "is_reverse_charge": 0,
            "is_export_with_gst": 0,
            "is_return": 0,
            "is_debit_note": 0,
            "return_against": None,
            "invoice_total": 400000.0,
            "returned_invoice_total": 0.0,
            "gst_category": "Overseas",
            "gst_treatment": "Zero-Rated",
            "gst_rate": 0.0,
            "taxable_value": 400000.0,
            "cgst_amount": 0.0,
            "sgst_amount": 0.0,
            "igst_amount": 0.0,
            "cess_amount": 0.0,
            "cess_non_advol_amount": 0.0,
            "total_cess_amount": 0.0,
            "total_tax": 0.0,
            "total_amount": 400000.0,
            "invoice_category": "Exports",
            "invoice_sub_category": "EXPWOP",
            "invoice_type": "WOPAY",
        },
        {
            "item_code": "_Test Trading Goods 1",
            "gst_hsn_code": "61149090",
            "uom": "Nos",
            "billing_address_gstin": None,
            "company_gstin": "24AAQCA8719H1ZC",
            "customer_name": "_Test Foreign Customer",
            "posting_date": today,
            "place_of_supply": "96-Other Countries",
            "is_reverse_charge": 0,
            "is_export_with_gst": 1,
            "is_return": 0,
            "is_debit_note": 0,
            "return_against": None,
            "invoice_total": 400000.0,
            "returned_invoice_total": 0.0,
            "gst_category": "Overseas",
            "gst_treatment": "Zero-Rated",
            "gst_rate": 0.0,
            "taxable_value": 400000.0,
            "cgst_amount": 0.0,
            "sgst_amount": 0.0,
            "igst_amount": 0.0,
            "cess_amount": 0.0,
            "cess_non_advol_amount": 0.0,
            "total_cess_amount": 0.0,
            "total_tax": 0.0,
            "total_amount": 400000.0,
            "invoice_category": "Exports",
            "invoice_sub_category": "EXPWP",
            "invoice_type": "WPAY",
        },
        {
            "item_code": "_Test Trading Goods 1",
            "gst_hsn_code": "61149090",
            "uom": "Nos",
            "billing_address_gstin": None,
            "company_gstin": "24AAQCA8719H1ZC",
            "customer_name": "_Test Foreign Customer",
            "posting_date": today,
            "place_of_supply": "96-Other Countries",
            "is_reverse_charge": 0,
            "is_export_with_gst": 0,
            "is_return": 1,
            "is_debit_note": 0,
            "return_against": None,
            "invoice_total": -400000.0,
            "returned_invoice_total": 0.0,
            "gst_category": "Overseas",
            "gst_treatment": "Zero-Rated",
            "gst_rate": 0.0,
            "taxable_value": -400000.0,
            "cgst_amount": 0.0,
            "sgst_amount": 0.0,
            "igst_amount": 0.0,
            "cess_amount": 0.0,
            "cess_non_advol_amount": 0.0,
            "total_cess_amount": 0.0,
            "total_tax": 0.0,
            "total_amount": -400000.0,
            "invoice_category": "Credit/Debit Notes (Unregistered)",
            "invoice_sub_category": "CDNUR",
            "invoice_type": "EXPWOP",
        },
    ],
    "SUMMARY_BY_HSN": [
        {
            "item_code": "_Test Trading Goods 1",
            "gst_hsn_code": "61149090",
            "uom": "Nos",
            "billing_address_gstin": None,
            "company_gstin": "24AAQCA8719H1ZC",
            "customer_name": "_Test Unregistered Customer",
            "posting_date": today,
            "place_of_supply": "29-Karnataka",
            "is_reverse_charge": 0,
            "is_export_with_gst": 0,
            "is_return": 0,
            "is_debit_note": 0,
            "return_against": None,
            "invoice_total": 472000.0,
            "returned_invoice_total": 0.0,
            "gst_category": "Unregistered",
            "gst_treatment": "Taxable",
            "gst_rate": 18.0,
            "taxable_value": 400000.0,
            "cgst_amount": 0.0,
            "sgst_amount": 0.0,
            "igst_amount": 72000.0,
            "cess_amount": 0.0,
            "cess_non_advol_amount": 0.0,
            "total_cess_amount": 0.0,
            "total_tax": 72000.0,
            "total_amount": 472000.0,
            "total_tax_amount": 72000.0,
            "invoice_category": "B2C (Large)",
            "invoice_sub_category": "B2C (Large)",
        },
        {
            "item_code": "_Test Trading Goods 1",
            "gst_hsn_code": "61149090",
            "uom": "Nos",
            "billing_address_gstin": None,
            "company_gstin": "24AAQCA8719H1ZC",
            "customer_name": "_Test Unregistered Customer",
            "posting_date": today,
            "place_of_supply": "24-Gujarat",
            "is_reverse_charge": 0,
            "is_export_with_gst": 0,
            "is_return": 0,
            "is_debit_note": 0,
            "return_against": None,
            "invoice_total": 472000.0,
            "returned_invoice_total": 0.0,
            "gst_category": "Unregistered",
            "gst_treatment": "Taxable",
            "gst_rate": 18.0,
            "taxable_value": 400000.0,
            "cgst_amount": 36000.0,
            "sgst_amount": 36000.0,
            "igst_amount": 0.0,
            "cess_amount": 0.0,
            "cess_non_advol_amount": 0.0,
            "total_cess_amount": 0.0,
            "total_tax": 72000.0,
            "total_amount": 472000.0,
            "total_tax_amount": 72000.0,
            "invoice_category": "B2C (Others)",
            "invoice_sub_category": "B2C (Others)",
        },
        {
            "item_code": "_Test Nil Rated Item",
            "gst_hsn_code": "61149090",
            "uom": "Nos",
            "billing_address_gstin": None,
            "company_gstin": "24AAQCA8719H1ZC",
            "customer_name": "_Test Unregistered Customer",
            "posting_date": today,
            "place_of_supply": "24-Gujarat",
            "is_reverse_charge": 0,
            "is_export_with_gst": 0,
            "is_return": 0,
            "is_debit_note": 0,
            "return_against": None,
            "invoice_total": 400000.0,
            "returned_invoice_total": 0.0,
            "gst_category": "Unregistered",
            "gst_treatment": "Nil-Rated",
            "gst_rate": 0.0,
            "taxable_value": 400000.0,
            "cgst_amount": 0.0,
            "sgst_amount": 0.0,
            "igst_amount": 0.0,
            "cess_amount": 0.0,
            "cess_non_advol_amount": 0.0,
            "total_cess_amount": 0.0,
            "total_tax": 0.0,
            "total_amount": 400000.0,
            "total_tax_amount": 0.0,
            "invoice_category": "Nil-Rated,Exempted,Non-GST",
            "invoice_type": "Intra-State to unregistered persons",
            "invoice_sub_category": "Nil-Rated",
        },
        {
            "item_code": "_Test Trading Goods 1",
            "gst_hsn_code": "61149090",
            "uom": "Nos",
            "billing_address_gstin": "29AABCR1718E1ZL",
            "company_gstin": "24AAQCA8719H1ZC",
            "customer_name": "_Test Registered Composition Customer",
            "posting_date": today,
            "place_of_supply": "29-Karnataka",
            "is_reverse_charge": 0,
            "is_export_with_gst": 0,
            "is_return": 0,
            "is_debit_note": 0,
            "return_against": None,
            "invoice_total": 472000.0,
            "returned_invoice_total": 0.0,
            "gst_category": "Registered Composition",
            "gst_treatment": "Taxable",
            "gst_rate": 18.0,
            "taxable_value": 400000.0,
            "cgst_amount": 0.0,
            "sgst_amount": 0.0,
            "igst_amount": 72000.0,
            "cess_amount": 0.0,
            "cess_non_advol_amount": 0.0,
            "total_cess_amount": 0.0,
            "total_tax": 72000.0,
            "total_amount": 472000.0,
            "total_tax_amount": 72000.0,
            "invoice_category": "B2B,SEZ,DE",
            "invoice_type": "Regular B2B",
            "invoice_sub_category": "B2B Regular",
        },
        {
            "item_code": "_Test Trading Goods 1",
            "gst_hsn_code": "61149090",
            "uom": "Nos",
            "billing_address_gstin": "29AABCR1718E1ZL",
            "company_gstin": "24AAQCA8719H1ZC",
            "customer_name": "_Test Registered Composition Customer",
            "posting_date": today,
            "place_of_supply": "29-Karnataka",
            "is_reverse_charge": 0,
            "is_export_with_gst": 0,
            "is_return": 1,
            "is_debit_note": 0,
            "return_against": None,
            "invoice_total": -472000.0,
            "returned_invoice_total": 0.0,
            "gst_category": "Registered Composition",
            "gst_treatment": "Taxable",
            "gst_rate": 18.0,
            "taxable_value": -400000.0,
            "cgst_amount": 0.0,
            "sgst_amount": 0.0,
            "igst_amount": -72000.0,
            "cess_amount": 0.0,
            "cess_non_advol_amount": 0.0,
            "total_cess_amount": 0.0,
            "total_tax": -72000.0,
            "total_amount": -472000.0,
            "total_tax_amount": -72000.0,
            "invoice_category": "Credit/Debit Notes (Registered)",
            "invoice_type": "Regular B2B",
            "invoice_sub_category": "CDNR",
        },
        {
            "item_code": "_Test Trading Goods 1",
            "gst_hsn_code": "61149090",
            "uom": "Nos",
            "billing_address_gstin": None,
            "company_gstin": "24AAQCA8719H1ZC",
            "customer_name": "_Test Foreign Customer",
            "posting_date": today,
            "place_of_supply": "96-Other Countries",
            "is_reverse_charge": 0,
            "is_export_with_gst": 0,
            "is_return": 0,
            "is_debit_note": 0,
            "return_against": None,
            "invoice_total": 400000.0,
            "returned_invoice_total": 0.0,
            "gst_category": "Overseas",
            "gst_treatment": "Zero-Rated",
            "gst_rate": 0.0,
            "taxable_value": 400000.0,
            "cgst_amount": 0.0,
            "sgst_amount": 0.0,
            "igst_amount": 0.0,
            "cess_amount": 0.0,
            "cess_non_advol_amount": 0.0,
            "total_cess_amount": 0.0,
            "total_tax": 0.0,
            "total_amount": 400000.0,
            "total_tax_amount": 0.0,
            "invoice_category": "Exports",
            "invoice_sub_category": "EXPWOP",
            "invoice_type": "WOPAY",
        },
        {
            "item_code": "_Test Trading Goods 1",
            "gst_hsn_code": "61149090",
            "uom": "Nos",
            "billing_address_gstin": None,
            "company_gstin": "24AAQCA8719H1ZC",
            "customer_name": "_Test Foreign Customer",
            "posting_date": today,
            "place_of_supply": "96-Other Countries",
            "is_reverse_charge": 0,
            "is_export_with_gst": 1,
            "is_return": 0,
            "is_debit_note": 0,
            "return_against": None,
            "invoice_total": 400000.0,
            "returned_invoice_total": 0.0,
            "gst_category": "Overseas",
            "gst_treatment": "Zero-Rated",
            "gst_rate": 0.0,
            "taxable_value": 400000.0,
            "cgst_amount": 0.0,
            "sgst_amount": 0.0,
            "igst_amount": 0.0,
            "cess_amount": 0.0,
            "cess_non_advol_amount": 0.0,
            "total_cess_amount": 0.0,
            "total_tax": 0.0,
            "total_amount": 400000.0,
            "total_tax_amount": 0.0,
            "invoice_category": "Exports",
            "invoice_sub_category": "EXPWP",
            "invoice_type": "WPAY",
        },
        {
            "item_code": "_Test Trading Goods 1",
            "gst_hsn_code": "61149090",
            "uom": "Nos",
            "billing_address_gstin": None,
            "company_gstin": "24AAQCA8719H1ZC",
            "customer_name": "_Test Foreign Customer",
            "posting_date": today,
            "place_of_supply": "96-Other Countries",
            "is_reverse_charge": 0,
            "is_export_with_gst": 0,
            "is_return": 1,
            "is_debit_note": 0,
            "return_against": None,
            "invoice_total": -400000.0,
            "returned_invoice_total": 0.0,
            "gst_category": "Overseas",
            "gst_treatment": "Zero-Rated",
            "gst_rate": 0.0,
            "taxable_value": -400000.0,
            "cgst_amount": 0.0,
            "sgst_amount": 0.0,
            "igst_amount": 0.0,
            "cess_amount": 0.0,
            "cess_non_advol_amount": 0.0,
            "total_cess_amount": 0.0,
            "total_tax": 0.0,
            "total_amount": -400000.0,
            "total_tax_amount": 0.0,
            "invoice_category": "Credit/Debit Notes (Unregistered)",
            "invoice_sub_category": "CDNUR",
            "invoice_type": "EXPWOP",
        },
    ],
    "OVERVIEW": [
        {
            "description": "B2B Regular",
            "no_of_records": 1,
            "taxable_value": 400000.0,
            "igst_amount": 72000.0,
            "cgst_amount": 0.0,
            "sgst_amount": 0.0,
            "total_cess_amount": 0.0,
        },
        {
            "description": "B2B Reverse Charge",
            "no_of_records": 0,
            "taxable_value": 0,
            "igst_amount": 0,
            "cgst_amount": 0,
            "sgst_amount": 0,
            "total_cess_amount": 0,
        },
        {
            "description": "SEZ with payment",
            "no_of_records": 0,
            "taxable_value": 0,
            "igst_amount": 0,
            "cgst_amount": 0,
            "sgst_amount": 0,
            "total_cess_amount": 0,
        },
        {
            "description": "SEZ without payment",
            "no_of_records": 0,
            "taxable_value": 0,
            "igst_amount": 0,
            "cgst_amount": 0,
            "sgst_amount": 0,
            "total_cess_amount": 0,
        },
        {
            "description": "Deemed Exports",
            "no_of_records": 0,
            "taxable_value": 0,
            "igst_amount": 0,
            "cgst_amount": 0,
            "sgst_amount": 0,
            "total_cess_amount": 0,
        },
        {
            "description": "B2C (Large)",
            "no_of_records": 1,
            "taxable_value": 400000.0,
            "igst_amount": 72000.0,
            "cgst_amount": 0.0,
            "sgst_amount": 0.0,
            "total_cess_amount": 0.0,
        },
        {
            "description": "Exports with payment",
            "no_of_records": 1,
            "taxable_value": 400000.0,
            "igst_amount": 0.0,
            "cgst_amount": 0.0,
            "sgst_amount": 0.0,
            "total_cess_amount": 0.0,
        },
        {
            "description": "Exports without payment",
            "no_of_records": 1,
            "taxable_value": 400000.0,
            "igst_amount": 0.0,
            "cgst_amount": 0.0,
            "sgst_amount": 0.0,
            "total_cess_amount": 0.0,
        },
        {
            "description": "B2C (Others)",
            "no_of_records": 1,
            "taxable_value": 400000.0,
            "igst_amount": 0.0,
            "cgst_amount": 36000.0,
            "sgst_amount": 36000.0,
            "total_cess_amount": 0.0,
        },
        {
            "description": "Nil-Rated",
            "no_of_records": 1,
            "taxable_value": 400000.0,
            "igst_amount": 0.0,
            "cgst_amount": 0.0,
            "sgst_amount": 0.0,
            "total_cess_amount": 0.0,
        },
        {
            "description": "Exempted",
            "no_of_records": 0,
            "taxable_value": 0,
            "igst_amount": 0,
            "cgst_amount": 0,
            "sgst_amount": 0,
            "total_cess_amount": 0,
        },
        {
            "description": "Non-GST",
            "no_of_records": 0,
            "taxable_value": 0,
            "igst_amount": 0,
            "cgst_amount": 0,
            "sgst_amount": 0,
            "total_cess_amount": 0,
        },
        {
            "description": "Credit/Debit Notes (Registered)",
            "no_of_records": 1,
            "taxable_value": -400000.0,
            "igst_amount": -72000.0,
            "cgst_amount": 0.0,
            "sgst_amount": 0.0,
            "total_cess_amount": 0.0,
        },
        {
            "description": "Credit/Debit Notes (Unregistered)",
            "no_of_records": 1,
            "taxable_value": -400000.0,
            "igst_amount": 0.0,
            "cgst_amount": 0.0,
            "sgst_amount": 0.0,
            "total_cess_amount": 0.0,
        },
    ],
}

INVOICES = [
    {
        # B2C (large)
        "item_code": "_Test Trading Goods 1",
        "customer": "_Test Unregistered Customer",
        "place_of_supply": "29-Karnataka",
        "rate": 2000,
        "qty": 200,
        "is_out_state": 1,
    },
    {
        # B2CS
        "item_code": "_Test Trading Goods 1",
        "customer": "_Test Unregistered Customer",
        "place_of_supply": "24-Gujarat",
        "rate": 2000,
        "qty": 200,
        "is_in_state": 1,
    },
    {
        # Nil-rated
        "item_code": "_Test Nil Rated Item",
        "company_gstin": "24AAQCA8719H1ZC",
        "customer": "_Test Unregistered Customer",
        "place_of_supply": "24-Gujarat",
        "rate": 2000,
        "qty": 200,
        "is_in_state": 1,
    },
    {
        # B2B Regular
        "item_code": "_Test Trading Goods 1",
        "company_gstin": "24AAQCA8719H1ZC",
        "customer": "_Test Registered Composition Customer",
        "place_of_supply": "29-Karnataka",
        "rate": 2000,
        "qty": 200,
        "is_out_state": 1,
    },
    {
        # CDNR
        "item_code": "_Test Trading Goods 1",
        "company_gstin": "24AAQCA8719H1ZC",
        "customer": "_Test Registered Composition Customer",
        "place_of_supply": "29-Karnataka",
        "rate": 2000,
        "qty": -200,
        "is_return": 1,
        "is_out_state": 1,
    },
    {
        # exports EXWOP
        "item_code": "_Test Trading Goods 1",
        "company_gstin": "24AAQCA8719H1ZC",
        "customer": "_Test Foreign Customer",
        "place_of_supply": "96-Other Countries",
        "rate": 2000,
        "qty": 200,
    },
    {
        # exports EXWP
        "item_code": "_Test Trading Goods 1",
        "company_gstin": "24AAQCA8719H1ZC",
        "customer": "_Test Foreign Customer",
        "place_of_supply": "96-Other Countries",
        "rate": 2000,
        "qty": 200,
        "is_export_with_gst": 1,
    },
    {
        # CDNUR
        "item_code": "_Test Trading Goods 1",
        "company_gstin": "24AAQCA8719H1ZC",
        "customer": "_Test Foreign Customer",
        "place_of_supply": "96-Other Countries",
        "rate": 2000,
        "qty": -200,
        "is_return": 1,
    },
]


class TestSalesRegisterBeta(FrappeTestCase):
    @classmethod
    @change_settings("GST Settings", {"enable_overseas_transactions": 1})
    def setUpClass(cls):
        super().setUpClass()
        TestSalesRegisterBeta().create_sales_invoices()

    def create_sales_invoices(self):
        for index, invoice in enumerate(INVOICES):
            inv = create_sales_invoice(**invoice)
            EXPECTED_OUTPUT["SUMMARY_BY_ITEM"][index]["invoice_no"] = inv.name
            EXPECTED_OUTPUT["SUMMARY_BY_HSN"][index]["invoice_no"] = inv.name

    def test_summary_by_item(self):
        FILTERS["summary_by"] = "Summary by Item"
        report_data = execute(FILTERS)

        for index, invoice in enumerate(report_data[1]):
            self.assertDictEqual(invoice, EXPECTED_OUTPUT["SUMMARY_BY_ITEM"][index])

    def test_summary_by_hsn(self):
        FILTERS["summary_by"] = "Summary by HSN"
        report_data = execute(FILTERS)

        EXPECTED_OUTPUT[
            "SUMMARY_BY_HSN"
        ].reverse()  # Summary by HSN are ordered by posting date

        for index, invoice in enumerate(report_data[1]):
            self.assertDictEqual(invoice, EXPECTED_OUTPUT["SUMMARY_BY_HSN"][index])

    def test_overview(self):
        FILTERS["summary_by"] = "Overview"
        report_data = execute(FILTERS)

        for index, invoice in enumerate(report_data[1]):
            del invoice["unique_records"]
            self.assertDictEqual(invoice, EXPECTED_OUTPUT["OVERVIEW"][index])
