from frappe.tests.utils import FrappeTestCase, change_settings
from frappe.utils import getdate

from india_compliance.gst_india.report.gst_sales_register_beta.gst_sales_register_beta import (
    execute,
)
from india_compliance.gst_india.utils.tests import create_sales_invoice

today = getdate()

FILTERS = {
    "company": "_Test Indian Registered Company",
    "date_range": [today, today],
    "from_date": today,
    "to_date": today,
}


EXPECTED_SUMMARY_BY_HSN = [
    {
        "item_code": "_Test Service Item",
        "gst_hsn_code": "999900",
        "billing_address_gstin": None,
        "company_gstin": "24AAQCA8719H1ZC",
        "customer_name": "_Test Foreign Customer",
        "place_of_supply": "96-Other Countries",
        "invoice_total": -405000.0,
        "returned_invoice_total": 0.0,
        "gst_category": "Overseas",
        "gst_treatment": "Zero-Rated",
        "gst_rate": 0.0,
        "taxable_value": -400000.0,
        "cess_non_advol_amount": 0.0,
        "total_cess_amount": 0.0,
        "total_amount": -400000.0,
        "total_tax_amount": 0.0,
        "invoice_category": "Credit/Debit Notes (Unregistered)",
        "invoice_sub_category": "CDNUR",
        "invoice_type": "EXPWOP",
    },
    {
        "item_code": "_Test Nil Rated Item",
        "gst_hsn_code": "61149090",
        "billing_address_gstin": None,
        "company_gstin": "24AAQCA8719H1ZC",
        "customer_name": "_Test Foreign Customer",
        "place_of_supply": "96-Other Countries",
        "invoice_total": -405000.0,
        "returned_invoice_total": 0.0,
        "gst_category": "Overseas",
        "gst_treatment": "Zero-Rated",
        "gst_rate": 0.0,
        "taxable_value": -5000.0,
        "cess_non_advol_amount": 0.0,
        "total_cess_amount": 0.0,
        "total_amount": -5000.0,
        "total_tax_amount": 0.0,
        "invoice_category": "Credit/Debit Notes (Unregistered)",
        "invoice_sub_category": "CDNUR",
        "invoice_type": "EXPWOP",
    },
    {
        "item_code": "_Test Service Item",
        "gst_hsn_code": "999900",
        "billing_address_gstin": None,
        "company_gstin": "24AAQCA8719H1ZC",
        "customer_name": "_Test Foreign Customer",
        "place_of_supply": "96-Other Countries",
        "invoice_total": 405000.0,
        "returned_invoice_total": 0.0,
        "gst_category": "Overseas",
        "gst_treatment": "Zero-Rated",
        "gst_rate": 0.0,
        "taxable_value": 400000.0,
        "cess_non_advol_amount": 0.0,
        "total_cess_amount": 0.0,
        "total_amount": 400000.0,
        "total_tax_amount": 0.0,
        "invoice_category": "Exports",
        "invoice_sub_category": "EXPWP",
        "invoice_type": "WPAY",
    },
    {
        "item_code": "_Test Nil Rated Item",
        "gst_hsn_code": "61149090",
        "billing_address_gstin": None,
        "company_gstin": "24AAQCA8719H1ZC",
        "customer_name": "_Test Foreign Customer",
        "place_of_supply": "96-Other Countries",
        "invoice_total": 405000.0,
        "returned_invoice_total": 0.0,
        "gst_category": "Overseas",
        "gst_treatment": "Zero-Rated",
        "gst_rate": 0.0,
        "taxable_value": 5000.0,
        "cess_non_advol_amount": 0.0,
        "total_cess_amount": 0.0,
        "total_amount": 5000.0,
        "total_tax_amount": 0.0,
        "invoice_category": "Exports",
        "invoice_sub_category": "EXPWP",
        "invoice_type": "WPAY",
    },
    {
        "item_code": "_Test Service Item",
        "gst_hsn_code": "999900",
        "billing_address_gstin": None,
        "company_gstin": "24AAQCA8719H1ZC",
        "customer_name": "_Test Foreign Customer",
        "place_of_supply": "96-Other Countries",
        "invoice_total": 405000.0,
        "returned_invoice_total": 0.0,
        "gst_category": "Overseas",
        "gst_treatment": "Zero-Rated",
        "gst_rate": 0.0,
        "taxable_value": 400000.0,
        "cess_non_advol_amount": 0.0,
        "total_cess_amount": 0.0,
        "total_amount": 400000.0,
        "total_tax_amount": 0.0,
        "invoice_category": "Exports",
        "invoice_sub_category": "EXPWOP",
        "invoice_type": "WOPAY",
    },
    {
        "item_code": "_Test Nil Rated Item",
        "gst_hsn_code": "61149090",
        "billing_address_gstin": None,
        "company_gstin": "24AAQCA8719H1ZC",
        "customer_name": "_Test Foreign Customer",
        "place_of_supply": "96-Other Countries",
        "invoice_total": 405000.0,
        "returned_invoice_total": 0.0,
        "gst_category": "Overseas",
        "gst_treatment": "Zero-Rated",
        "gst_rate": 0.0,
        "taxable_value": 5000.0,
        "cess_non_advol_amount": 0.0,
        "total_cess_amount": 0.0,
        "total_amount": 5000.0,
        "total_tax_amount": 0.0,
        "invoice_category": "Exports",
        "invoice_sub_category": "EXPWOP",
        "invoice_type": "WOPAY",
    },
    {
        "item_code": "_Test Service Item",
        "gst_hsn_code": "999900",
        "billing_address_gstin": "29AABCR1718E1ZL",
        "company_gstin": "24AAQCA8719H1ZC",
        "customer_name": "_Test Registered Composition Customer",
        "place_of_supply": "29-Karnataka",
        "invoice_total": -477000.0,
        "returned_invoice_total": 0.0,
        "gst_category": "Registered Composition",
        "gst_treatment": "Taxable",
        "gst_rate": 18.0,
        "taxable_value": -400000.0,
        "cess_non_advol_amount": 0.0,
        "total_cess_amount": 0.0,
        "total_amount": -472000.0,
        "total_tax_amount": -72000.0,
        "invoice_category": "Credit/Debit Notes (Registered)",
        "invoice_type": "Regular B2B",
        "invoice_sub_category": "CDNR",
    },
    {
        "item_code": "_Test Nil Rated Item",
        "gst_hsn_code": "61149090",
        "billing_address_gstin": "29AABCR1718E1ZL",
        "company_gstin": "24AAQCA8719H1ZC",
        "customer_name": "_Test Registered Composition Customer",
        "place_of_supply": "29-Karnataka",
        "invoice_total": -477000.0,
        "returned_invoice_total": 0.0,
        "gst_category": "Registered Composition",
        "gst_treatment": "Nil-Rated",
        "gst_rate": 0.0,
        "taxable_value": -5000.0,
        "cess_non_advol_amount": 0.0,
        "total_cess_amount": 0.0,
        "total_amount": -5000.0,
        "total_tax_amount": 0.0,
        "invoice_category": "Nil-Rated,Exempted,Non-GST",
        "invoice_type": "Inter-State to registered persons",
        "invoice_sub_category": "Nil-Rated",
    },
    {
        "item_code": "_Test Service Item",
        "gst_hsn_code": "999900",
        "billing_address_gstin": "29AABCR1718E1ZL",
        "company_gstin": "24AAQCA8719H1ZC",
        "customer_name": "_Test Registered Composition Customer",
        "place_of_supply": "29-Karnataka",
        "invoice_total": 477000.0,
        "returned_invoice_total": 0.0,
        "gst_category": "Registered Composition",
        "gst_treatment": "Taxable",
        "gst_rate": 18.0,
        "taxable_value": 400000.0,
        "cess_non_advol_amount": 0.0,
        "total_cess_amount": 0.0,
        "total_amount": 472000.0,
        "total_tax_amount": 72000.0,
        "invoice_category": "B2B,SEZ,DE",
        "invoice_type": "Regular B2B",
        "invoice_sub_category": "B2B Regular",
    },
    {
        "item_code": "_Test Nil Rated Item",
        "gst_hsn_code": "61149090",
        "billing_address_gstin": "29AABCR1718E1ZL",
        "company_gstin": "24AAQCA8719H1ZC",
        "customer_name": "_Test Registered Composition Customer",
        "place_of_supply": "29-Karnataka",
        "invoice_total": 477000.0,
        "returned_invoice_total": 0.0,
        "gst_category": "Registered Composition",
        "gst_treatment": "Nil-Rated",
        "gst_rate": 0.0,
        "taxable_value": 5000.0,
        "cess_non_advol_amount": 0.0,
        "total_cess_amount": 0.0,
        "total_amount": 5000.0,
        "total_tax_amount": 0.0,
        "invoice_category": "Nil-Rated,Exempted,Non-GST",
        "invoice_type": "Inter-State to registered persons",
        "invoice_sub_category": "Nil-Rated",
    },
    {
        "item_code": "_Test Service Item",
        "gst_hsn_code": "999900",
        "billing_address_gstin": None,
        "company_gstin": "24AAQCA8719H1ZC",
        "customer_name": "_Test Unregistered Customer",
        "place_of_supply": "24-Gujarat",
        "invoice_total": 477000.0,
        "returned_invoice_total": 0.0,
        "gst_category": "Unregistered",
        "gst_treatment": "Taxable",
        "gst_rate": 18.0,
        "taxable_value": 400000.0,
        "cess_non_advol_amount": 0.0,
        "total_cess_amount": 0.0,
        "total_amount": 472000.0,
        "total_tax_amount": 72000.0,
        "invoice_category": "B2C (Others)",
        "invoice_sub_category": "B2C (Others)",
    },
    {
        "item_code": "_Test Nil Rated Item",
        "gst_hsn_code": "61149090",
        "billing_address_gstin": None,
        "company_gstin": "24AAQCA8719H1ZC",
        "customer_name": "_Test Unregistered Customer",
        "place_of_supply": "24-Gujarat",
        "invoice_total": 477000.0,
        "returned_invoice_total": 0.0,
        "gst_category": "Unregistered",
        "gst_treatment": "Nil-Rated",
        "gst_rate": 0.0,
        "taxable_value": 5000.0,
        "cess_non_advol_amount": 0.0,
        "total_cess_amount": 0.0,
        "total_amount": 5000.0,
        "total_tax_amount": 0.0,
        "invoice_category": "Nil-Rated,Exempted,Non-GST",
        "invoice_type": "Intra-State to unregistered persons",
        "invoice_sub_category": "Nil-Rated",
    },
    {
        "item_code": "_Test Service Item",
        "gst_hsn_code": "999900",
        "billing_address_gstin": None,
        "company_gstin": "24AAQCA8719H1ZC",
        "customer_name": "_Test Unregistered Customer",
        "place_of_supply": "24-Gujarat",
        "invoice_total": 477000.0,
        "returned_invoice_total": 0.0,
        "gst_category": "Unregistered",
        "gst_treatment": "Taxable",
        "gst_rate": 18.0,
        "taxable_value": 400000.0,
        "cess_non_advol_amount": 0.0,
        "total_cess_amount": 0.0,
        "total_amount": 472000.0,
        "total_tax_amount": 72000.0,
        "invoice_category": "B2C (Others)",
        "invoice_sub_category": "B2C (Others)",
    },
    {
        "item_code": "_Test Nil Rated Item",
        "gst_hsn_code": "61149090",
        "billing_address_gstin": None,
        "company_gstin": "24AAQCA8719H1ZC",
        "customer_name": "_Test Unregistered Customer",
        "place_of_supply": "24-Gujarat",
        "invoice_total": 477000.0,
        "returned_invoice_total": 0.0,
        "gst_category": "Unregistered",
        "gst_treatment": "Nil-Rated",
        "gst_rate": 0.0,
        "taxable_value": 5000.0,
        "cess_non_advol_amount": 0.0,
        "total_cess_amount": 0.0,
        "total_amount": 5000.0,
        "total_tax_amount": 0.0,
        "invoice_category": "Nil-Rated,Exempted,Non-GST",
        "invoice_type": "Intra-State to unregistered persons",
        "invoice_sub_category": "Nil-Rated",
    },
    {
        "item_code": "_Test Service Item",
        "gst_hsn_code": "999900",
        "billing_address_gstin": None,
        "company_gstin": "24AAQCA8719H1ZC",
        "customer_name": "_Test Unregistered Customer",
        "place_of_supply": "29-Karnataka",
        "invoice_total": 477000.0,
        "returned_invoice_total": 0.0,
        "gst_category": "Unregistered",
        "gst_treatment": "Taxable",
        "gst_rate": 18.0,
        "taxable_value": 400000.0,
        "cess_non_advol_amount": 0.0,
        "total_cess_amount": 0.0,
        "total_amount": 472000.0,
        "total_tax_amount": 72000.0,
        "invoice_category": "B2C (Large)",
        "invoice_sub_category": "B2C (Large)",
    },
    {
        "item_code": "_Test Nil Rated Item",
        "gst_hsn_code": "61149090",
        "billing_address_gstin": None,
        "company_gstin": "24AAQCA8719H1ZC",
        "customer_name": "_Test Unregistered Customer",
        "place_of_supply": "29-Karnataka",
        "invoice_total": 477000.0,
        "returned_invoice_total": 0.0,
        "gst_category": "Unregistered",
        "gst_treatment": "Nil-Rated",
        "gst_rate": 0.0,
        "taxable_value": 5000.0,
        "cess_non_advol_amount": 0.0,
        "total_cess_amount": 0.0,
        "total_amount": 5000.0,
        "total_tax_amount": 0.0,
        "invoice_category": "Nil-Rated,Exempted,Non-GST",
        "invoice_type": "Inter-State to unregistered persons",
        "invoice_sub_category": "Nil-Rated",
    },
]
EXPECTED_OVERVIEW = [
    {
        "description": "B2B Regular",
        "no_of_records": 1,
        "taxable_value": 400000.0,
        "igst_amount": 72000.0,
        "cgst_amount": 0.0,
        "sgst_amount": 0.0,
        "total_cess_amount": 0.0,
    },
    {
        "description": "B2B Reverse Charge",
        "no_of_records": 0,
        "taxable_value": 0,
        "igst_amount": 0,
        "cgst_amount": 0,
        "sgst_amount": 0,
        "total_cess_amount": 0,
    },
    {
        "description": "SEZ with payment",
        "no_of_records": 0,
        "taxable_value": 0,
        "igst_amount": 0,
        "cgst_amount": 0,
        "sgst_amount": 0,
        "total_cess_amount": 0,
    },
    {
        "description": "SEZ without payment",
        "no_of_records": 0,
        "taxable_value": 0,
        "igst_amount": 0,
        "cgst_amount": 0,
        "sgst_amount": 0,
        "total_cess_amount": 0,
    },
    {
        "description": "Deemed Exports",
        "no_of_records": 0,
        "taxable_value": 0,
        "igst_amount": 0,
        "cgst_amount": 0,
        "sgst_amount": 0,
        "total_cess_amount": 0,
    },
    {
        "description": "B2C (Large)",
        "no_of_records": 1,
        "taxable_value": 400000.0,
        "igst_amount": 72000.0,
        "cgst_amount": 0.0,
        "sgst_amount": 0.0,
        "total_cess_amount": 0.0,
    },
    {
        "description": "Exports with payment",
        "no_of_records": 1,
        "taxable_value": 405000.0,
        "igst_amount": 0.0,
        "cgst_amount": 0.0,
        "sgst_amount": 0.0,
        "total_cess_amount": 0.0,
    },
    {
        "description": "Exports without payment",
        "no_of_records": 1,
        "taxable_value": 405000.0,
        "igst_amount": 0.0,
        "cgst_amount": 0.0,
        "sgst_amount": 0.0,
        "total_cess_amount": 0.0,
    },
    {
        "description": "B2C (Others)",
        "no_of_records": 2,
        "taxable_value": 800000.0,
        "igst_amount": 0.0,
        "cgst_amount": 72000.0,
        "sgst_amount": 72000.0,
        "total_cess_amount": 0.0,
    },
    {
        "description": "Nil-Rated",
        "no_of_records": 5,
        "taxable_value": 15000.0,
        "igst_amount": 0.0,
        "cgst_amount": 0.0,
        "sgst_amount": 0.0,
        "total_cess_amount": 0.0,
    },
    {
        "description": "Exempted",
        "no_of_records": 0,
        "taxable_value": 0,
        "igst_amount": 0,
        "cgst_amount": 0,
        "sgst_amount": 0,
        "total_cess_amount": 0,
    },
    {
        "description": "Non-GST",
        "no_of_records": 0,
        "taxable_value": 0,
        "igst_amount": 0,
        "cgst_amount": 0,
        "sgst_amount": 0,
        "total_cess_amount": 0,
    },
    {
        "description": "Credit/Debit Notes (Registered)",
        "no_of_records": 1,
        "taxable_value": -400000.0,
        "igst_amount": -72000.0,
        "cgst_amount": 0.0,
        "sgst_amount": 0.0,
        "total_cess_amount": 0.0,
    },
    {
        "description": "Credit/Debit Notes (Unregistered)",
        "no_of_records": 1,
        "taxable_value": -405000.0,
        "igst_amount": 0.0,
        "cgst_amount": 0.0,
        "sgst_amount": 0.0,
        "total_cess_amount": 0.0,
    },
]

INVOICES = [
    {
        "customer": "_Test Unregistered Customer",
        "place_of_supply": "29-Karnataka",
        "is_out_state": 1,
        "item_code": "_Test Service Item",
        "rate": 2000,
        "qty": 200,
        "items": [
            {
                "item_code": "_Test Nil Rated Item",
                "rate": 100,
                "qty": 50,
            },
        ],
    },
    {
        # B2CS
        "customer": "_Test Unregistered Customer",
        "place_of_supply": "24-Gujarat",
        "is_in_state": 1,
        "item_code": "_Test Service Item",
        "rate": 2000,
        "qty": 200,
        "items": [
            {
                "item_code": "_Test Nil Rated Item",
                "rate": 100,
                "qty": 50,
            },
        ],
    },
    {
        "company_gstin": "24AAQCA8719H1ZC",
        "customer": "_Test Unregistered Customer",
        "place_of_supply": "24-Gujarat",
        "is_in_state": 1,
        "item_code": "_Test Service Item",
        "rate": 2000,
        "qty": 200,
        "items": [
            {
                "item_code": "_Test Nil Rated Item",
                "rate": 100,
                "qty": 50,
            },
        ],
    },
    {
        # B2B Regular
        "company_gstin": "24AAQCA8719H1ZC",
        "customer": "_Test Registered Composition Customer",
        "place_of_supply": "29-Karnataka",
        "is_out_state": 1,
        "item_code": "_Test Service Item",
        "rate": 2000,
        "qty": 200,
        "items": [
            {
                "item_code": "_Test Nil Rated Item",
                "rate": 100,
                "qty": 50,
            }
        ],
    },
    {
        "company_gstin": "24AAQCA8719H1ZC",
        "customer": "_Test Registered Composition Customer",
        "place_of_supply": "29-Karnataka",
        "is_return": 1,
        "is_out_state": 1,
        "item_code": "_Test Service Item",
        "rate": 2000,
        "qty": -200,
        "items": [
            {
                "item_code": "_Test Nil Rated Item",
                "rate": 100,
                "qty": -50,
            }
        ],
    },
    {
        "company_gstin": "24AAQCA8719H1ZC",
        "customer": "_Test Foreign Customer",
        "place_of_supply": "96-Other Countries",
        "item_code": "_Test Service Item",
        "rate": 2000,
        "qty": 200,
        "items": [
            {
                "item_code": "_Test Nil Rated Item",
                "rate": 100,
                "qty": 50,
            }
        ],
    },
    {
        "company_gstin": "24AAQCA8719H1ZC",
        "customer": "_Test Foreign Customer",
        "place_of_supply": "96-Other Countries",
        "is_export_with_gst": 1,
        "item_code": "_Test Service Item",
        "rate": 2000,
        "qty": 200,
        "items": [
            {
                "item_code": "_Test Nil Rated Item",
                "rate": 100,
                "qty": 50,
            }
        ],
    },
    {
        "company_gstin": "24AAQCA8719H1ZC",
        "customer": "_Test Foreign Customer",
        "place_of_supply": "96-Other Countries",
        "is_return": 1,
        "item_code": "_Test Service Item",
        "rate": 2000,
        "qty": -200,
        "items": [
            {
                "item_code": "_Test Nil Rated Item",
                "rate": 100,
                "qty": -50,
            }
        ],
    },
]


class TestSalesRegisterBeta(FrappeTestCase):
    @classmethod
    @change_settings("GST Settings", {"enable_overseas_transactions": 1})
    def setUpClass(cls):
        TestSalesRegisterBeta().create_sales_invoices()

    def create_sales_invoices(self):
        for invoice in INVOICES:
            create_sales_invoice(**invoice)

    def test_summary_by_hsn(self):
        FILTERS["summary_by"] = "Summary by HSN"
        report_data = execute(FILTERS)

        for index, invoice in enumerate(report_data[1]):
            self.assertPartialDict(EXPECTED_SUMMARY_BY_HSN[index], invoice)

    def test_overview(self):
        FILTERS["summary_by"] = "Overview"
        report_data = execute(FILTERS)

        for index, invoice in enumerate(report_data[1]):
            self.assertPartialDict(EXPECTED_OVERVIEW[index], invoice)

    def assertPartialDict(self, d1, d2, msg=None):
        self.assertIsInstance(d1, dict, "First argument is not a dictionary")
        self.assertIsInstance(d2, dict, "Second argument is not a dictionary")

        if d1 != d2:
            for key in d1:
                if d1[key] != d2[key]:
                    standardMsg = f"{key}: {d1[key]} != {d2[key]}"
                    self.fail(self._formatMessage(msg, standardMsg))
